### ISSUE TITLE
Request to release v1.3.0

### ISSUE THREAD

**Issue by adamgeorgeson** [abepetrillo/evergreen#90]
Hey!

I came across a need to override the default `Evergreen.spec_timeout` value. It wasn't until I tried it that I realised that change never got released.

Would it be possible to release a v1.3.0 from master?

[1.2.0...master](https://github.com/abepetrillo/evergreen/compare/1.2.0...master)
#83 - PR I am most interested in.

Cheers!
Adam.

**Comment by abepetrillo** [comment]
Yes. I'll try get to it this weekend.
